/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirecteurRouteImport } from './routes/directeur'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as BoRouteImport } from './routes/bo'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirecteurIndexRouteImport } from './routes/directeur.index'
import { Route as ChefIndexRouteImport } from './routes/chef.index'
import { Route as BoIndexRouteImport } from './routes/bo.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientSuiviRouteImport } from './routes/client.suivi'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientForgotPasswordRouteImport } from './routes/client.forgot-password'
import { Route as ClientDeposerRouteImport } from './routes/client.deposer'
import { Route as ChefAffectationAgentRouteImport } from './routes/chef.affectation-agent'
import { Route as BoCourrierSortantRouteImport } from './routes/bo.courrier-sortant'
import { Route as BoCourrierEntrantRouteImport } from './routes/bo.courrier-entrant'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as DirecteurCourrierIdRouteImport } from './routes/directeur.courrier.$id'
import { Route as DirecteurAffectationIdRouteImport } from './routes/directeur.affectation.$id'
import { Route as AgentCourrierIdRouteImport } from './routes/agent.courrier.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecteurRoute = DirecteurRouteImport.update({
  id: '/directeur',
  path: '/directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const BoRoute = BoRouteImport.update({
  id: '/bo',
  path: '/bo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecteurIndexRoute = DirecteurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirecteurRoute,
} as any)
const ChefIndexRoute = ChefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChefRoute,
} as any)
const BoIndexRoute = BoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientSuiviRoute = ClientSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientForgotPasswordRoute = ClientForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDeposerRoute = ClientDeposerRouteImport.update({
  id: '/deposer',
  path: '/deposer',
  getParentRoute: () => ClientRoute,
} as any)
const ChefAffectationAgentRoute = ChefAffectationAgentRouteImport.update({
  id: '/affectation-agent',
  path: '/affectation-agent',
  getParentRoute: () => ChefRoute,
} as any)
const BoCourrierSortantRoute = BoCourrierSortantRouteImport.update({
  id: '/courrier-sortant',
  path: '/courrier-sortant',
  getParentRoute: () => BoRoute,
} as any)
const BoCourrierEntrantRoute = BoCourrierEntrantRouteImport.update({
  id: '/courrier-entrant',
  path: '/courrier-entrant',
  getParentRoute: () => BoRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const DirecteurCourrierIdRoute = DirecteurCourrierIdRouteImport.update({
  id: '/courrier/$id',
  path: '/courrier/$id',
  getParentRoute: () => DirecteurRoute,
} as any)
const DirecteurAffectationIdRoute = DirecteurAffectationIdRouteImport.update({
  id: '/affectation/$id',
  path: '/affectation/$id',
  getParentRoute: () => DirecteurRoute,
} as any)
const AgentCourrierIdRoute = AgentCourrierIdRouteImport.update({
  id: '/courrier/$id',
  path: '/courrier/$id',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/bo': typeof BoRouteWithChildren
  '/chef': typeof ChefRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/directeur': typeof DirecteurRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/bo/courrier-entrant': typeof BoCourrierEntrantRoute
  '/bo/courrier-sortant': typeof BoCourrierSortantRoute
  '/chef/affectation-agent': typeof ChefAffectationAgentRoute
  '/client/deposer': typeof ClientDeposerRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/login': typeof ClientLoginRoute
  '/client/suivi': typeof ClientSuiviRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/bo/': typeof BoIndexRoute
  '/chef/': typeof ChefIndexRoute
  '/directeur/': typeof DirecteurIndexRoute
  '/agent/courrier/$id': typeof AgentCourrierIdRoute
  '/directeur/affectation/$id': typeof DirecteurAffectationIdRoute
  '/directeur/courrier/$id': typeof DirecteurCourrierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/bo/courrier-entrant': typeof BoCourrierEntrantRoute
  '/bo/courrier-sortant': typeof BoCourrierSortantRoute
  '/chef/affectation-agent': typeof ChefAffectationAgentRoute
  '/client/deposer': typeof ClientDeposerRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/login': typeof ClientLoginRoute
  '/client/suivi': typeof ClientSuiviRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/bo': typeof BoIndexRoute
  '/chef': typeof ChefIndexRoute
  '/directeur': typeof DirecteurIndexRoute
  '/agent/courrier/$id': typeof AgentCourrierIdRoute
  '/directeur/affectation/$id': typeof DirecteurAffectationIdRoute
  '/directeur/courrier/$id': typeof DirecteurCourrierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/bo': typeof BoRouteWithChildren
  '/chef': typeof ChefRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/directeur': typeof DirecteurRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/bo/courrier-entrant': typeof BoCourrierEntrantRoute
  '/bo/courrier-sortant': typeof BoCourrierSortantRoute
  '/chef/affectation-agent': typeof ChefAffectationAgentRoute
  '/client/deposer': typeof ClientDeposerRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/login': typeof ClientLoginRoute
  '/client/suivi': typeof ClientSuiviRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/bo/': typeof BoIndexRoute
  '/chef/': typeof ChefIndexRoute
  '/directeur/': typeof DirecteurIndexRoute
  '/agent/courrier/$id': typeof AgentCourrierIdRoute
  '/directeur/affectation/$id': typeof DirecteurAffectationIdRoute
  '/directeur/courrier/$id': typeof DirecteurCourrierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/bo'
    | '/chef'
    | '/client'
    | '/directeur'
    | '/login'
    | '/admin/services'
    | '/admin/utilisateurs'
    | '/bo/courrier-entrant'
    | '/bo/courrier-sortant'
    | '/chef/affectation-agent'
    | '/client/deposer'
    | '/client/forgot-password'
    | '/client/login'
    | '/client/suivi'
    | '/admin/'
    | '/agent/'
    | '/bo/'
    | '/chef/'
    | '/directeur/'
    | '/agent/courrier/$id'
    | '/directeur/affectation/$id'
    | '/directeur/courrier/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/login'
    | '/admin/services'
    | '/admin/utilisateurs'
    | '/bo/courrier-entrant'
    | '/bo/courrier-sortant'
    | '/chef/affectation-agent'
    | '/client/deposer'
    | '/client/forgot-password'
    | '/client/login'
    | '/client/suivi'
    | '/admin'
    | '/agent'
    | '/bo'
    | '/chef'
    | '/directeur'
    | '/agent/courrier/$id'
    | '/directeur/affectation/$id'
    | '/directeur/courrier/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/bo'
    | '/chef'
    | '/client'
    | '/directeur'
    | '/login'
    | '/admin/services'
    | '/admin/utilisateurs'
    | '/bo/courrier-entrant'
    | '/bo/courrier-sortant'
    | '/chef/affectation-agent'
    | '/client/deposer'
    | '/client/forgot-password'
    | '/client/login'
    | '/client/suivi'
    | '/admin/'
    | '/agent/'
    | '/bo/'
    | '/chef/'
    | '/directeur/'
    | '/agent/courrier/$id'
    | '/directeur/affectation/$id'
    | '/directeur/courrier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  BoRoute: typeof BoRouteWithChildren
  ChefRoute: typeof ChefRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DirecteurRoute: typeof DirecteurRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directeur': {
      id: '/directeur'
      path: '/directeur'
      fullPath: '/directeur'
      preLoaderRoute: typeof DirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bo': {
      id: '/bo'
      path: '/bo'
      fullPath: '/bo'
      preLoaderRoute: typeof BoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directeur/': {
      id: '/directeur/'
      path: '/'
      fullPath: '/directeur/'
      preLoaderRoute: typeof DirecteurIndexRouteImport
      parentRoute: typeof DirecteurRoute
    }
    '/chef/': {
      id: '/chef/'
      path: '/'
      fullPath: '/chef/'
      preLoaderRoute: typeof ChefIndexRouteImport
      parentRoute: typeof ChefRoute
    }
    '/bo/': {
      id: '/bo/'
      path: '/'
      fullPath: '/bo/'
      preLoaderRoute: typeof BoIndexRouteImport
      parentRoute: typeof BoRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/suivi': {
      id: '/client/suivi'
      path: '/suivi'
      fullPath: '/client/suivi'
      preLoaderRoute: typeof ClientSuiviRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/forgot-password': {
      id: '/client/forgot-password'
      path: '/forgot-password'
      fullPath: '/client/forgot-password'
      preLoaderRoute: typeof ClientForgotPasswordRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/deposer': {
      id: '/client/deposer'
      path: '/deposer'
      fullPath: '/client/deposer'
      preLoaderRoute: typeof ClientDeposerRouteImport
      parentRoute: typeof ClientRoute
    }
    '/chef/affectation-agent': {
      id: '/chef/affectation-agent'
      path: '/affectation-agent'
      fullPath: '/chef/affectation-agent'
      preLoaderRoute: typeof ChefAffectationAgentRouteImport
      parentRoute: typeof ChefRoute
    }
    '/bo/courrier-sortant': {
      id: '/bo/courrier-sortant'
      path: '/courrier-sortant'
      fullPath: '/bo/courrier-sortant'
      preLoaderRoute: typeof BoCourrierSortantRouteImport
      parentRoute: typeof BoRoute
    }
    '/bo/courrier-entrant': {
      id: '/bo/courrier-entrant'
      path: '/courrier-entrant'
      fullPath: '/bo/courrier-entrant'
      preLoaderRoute: typeof BoCourrierEntrantRouteImport
      parentRoute: typeof BoRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/directeur/courrier/$id': {
      id: '/directeur/courrier/$id'
      path: '/courrier/$id'
      fullPath: '/directeur/courrier/$id'
      preLoaderRoute: typeof DirecteurCourrierIdRouteImport
      parentRoute: typeof DirecteurRoute
    }
    '/directeur/affectation/$id': {
      id: '/directeur/affectation/$id'
      path: '/affectation/$id'
      fullPath: '/directeur/affectation/$id'
      preLoaderRoute: typeof DirecteurAffectationIdRouteImport
      parentRoute: typeof DirecteurRoute
    }
    '/agent/courrier/$id': {
      id: '/agent/courrier/$id'
      path: '/courrier/$id'
      fullPath: '/agent/courrier/$id'
      preLoaderRoute: typeof AgentCourrierIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminServicesRoute: typeof AdminServicesRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminServicesRoute: AdminServicesRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentIndexRoute: typeof AgentIndexRoute
  AgentCourrierIdRoute: typeof AgentCourrierIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentIndexRoute: AgentIndexRoute,
  AgentCourrierIdRoute: AgentCourrierIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface BoRouteChildren {
  BoCourrierEntrantRoute: typeof BoCourrierEntrantRoute
  BoCourrierSortantRoute: typeof BoCourrierSortantRoute
  BoIndexRoute: typeof BoIndexRoute
}

const BoRouteChildren: BoRouteChildren = {
  BoCourrierEntrantRoute: BoCourrierEntrantRoute,
  BoCourrierSortantRoute: BoCourrierSortantRoute,
  BoIndexRoute: BoIndexRoute,
}

const BoRouteWithChildren = BoRoute._addFileChildren(BoRouteChildren)

interface ChefRouteChildren {
  ChefAffectationAgentRoute: typeof ChefAffectationAgentRoute
  ChefIndexRoute: typeof ChefIndexRoute
}

const ChefRouteChildren: ChefRouteChildren = {
  ChefAffectationAgentRoute: ChefAffectationAgentRoute,
  ChefIndexRoute: ChefIndexRoute,
}

const ChefRouteWithChildren = ChefRoute._addFileChildren(ChefRouteChildren)

interface ClientRouteChildren {
  ClientDeposerRoute: typeof ClientDeposerRoute
  ClientForgotPasswordRoute: typeof ClientForgotPasswordRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientSuiviRoute: typeof ClientSuiviRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDeposerRoute: ClientDeposerRoute,
  ClientForgotPasswordRoute: ClientForgotPasswordRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientSuiviRoute: ClientSuiviRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DirecteurRouteChildren {
  DirecteurIndexRoute: typeof DirecteurIndexRoute
  DirecteurAffectationIdRoute: typeof DirecteurAffectationIdRoute
  DirecteurCourrierIdRoute: typeof DirecteurCourrierIdRoute
}

const DirecteurRouteChildren: DirecteurRouteChildren = {
  DirecteurIndexRoute: DirecteurIndexRoute,
  DirecteurAffectationIdRoute: DirecteurAffectationIdRoute,
  DirecteurCourrierIdRoute: DirecteurCourrierIdRoute,
}

const DirecteurRouteWithChildren = DirecteurRoute._addFileChildren(
  DirecteurRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  BoRoute: BoRouteWithChildren,
  ChefRoute: ChefRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DirecteurRoute: DirecteurRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
